# Generated by Django 4.1.7 on 2023-05-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lang_tutor_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_paying",
            field=models.BooleanField(default=False),
        ),
    ]
